Make the dumping of dmesg configurable
From 36281407d2f99ed8deb29a4f4c3d94506c1ccec5 Mon Sep 17 00:00:00 2001
From: Juerg Haefliger <juerg.haefliger@hp.com>
Date: Tue, 6 May 2014 07:44:45 +0000
Subject: [PATCH] Make the dumping of dmesg configurable

Dumping the dmesg buffer has shown to be problematic when kernels
change. This patch introduces a new config variable that can turn
the dmesg dump off.  The default behaviour unchanged, i.e., the
dmesg buffer is dumped.

Signed-off-by: Louis Bouchard <louis.bouchard@ubuntu.com>

diff --git a/debian/kdump-config b/debian/kdump-config
--- a/debian/kdump-config
+++ b/debian/kdump-config
@@ -45,6 +45,7 @@ ARCH=`uname -m`
 # Set up defaults
 KDUMP_SYSCTL=${KDUMP_SYSCTL:="kernel.panic_on_oops=1"}
 KDUMP_COREDIR=${KDUMP_COREDIR:=/var/crash}
+KDUMP_DUMP_DMESG=${KDUMP_DUMP_DMESG:=1}
 MAKEDUMP_ARGS=${MAKEDUMP_ARGS:="-c -d 31"}
 KDUMP_CMDLINE_APPEND=${KDUMP_CMDLINE_APPEND:="irqpoll maxcpus=1 nousb"}
 [ -d $KDUMP_COREDIR ] || mkdir -p $KDUMP_COREDIR ;
@@ -412,23 +413,25 @@ function kdump_save_core()
 		logger -t $NAME "failed to save vmcore in $KDUMP_STAMPDIR"
 	fi
 
-	log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE"
-	makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE
-	ERROR=$?
-	if [ $ERROR -ne 0 ] ; then
-		log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-		logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-	fi
+	# dump the dmesg buffer
+	if [ $KDUMP_DUMP_DMESG -eq 1 ] ; then
+            log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE"
+            makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE
+            ERROR=$?
+            if [ $ERROR -ne 0 ] ; then
+                log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+                logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+            fi
 
-	# did we succeed?
-	if [ $ERROR == 0 ]; then
+	    # did we succeed?
+	    if [ $ERROR == 0 ]; then
 		log_success_msg "$NAME: saved dmesg content in $KDUMP_STAMPDIR"
 		logger -t $NAME "saved dmesg content in $KDUMP_STAMPDIR"
-	else
+	    else
 		log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_STAMPDIR"
 		logger -t $NAME "failed to save dmesg content in $KDUMP_STAMPDIR"
+	    fi
 	fi
-
 	# If we use NFS, umount the remote FS
 	#
 	if [ -n "$NFS" ];then
@@ -495,26 +498,29 @@ function kdump_save_core_to_ssh()
 		logger -t $NAME "saved vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
 	fi
 
-	log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG"
-	makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG
-	ERROR=$?
-	if [ $ERROR -ne 0 ] ; then
-		log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-		logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-	else
-		scp -i $KDUMP_SSH_KEY $KDUMP_TMPDMESG $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE
-		ERROR=$?
-	fi
+	# dump the dmesg buffer
+        if [ $KDUMP_DUMP_DMESG -eq 1 ] ; then
+	    log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG"
+	    makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG
+	    ERROR=$?
+	    if [ $ERROR -ne 0 ] ; then
+		    log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+		    logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+	    else
+		    scp -i $KDUMP_SSH_KEY $KDUMP_TMPDMESG $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE
+		    ERROR=$?
+	    fi
 
-	# did we succeed?
-	if [ $ERROR == 0 ]; then
-		log_success_msg "$NAME: saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		logger -t $NAME "saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		return 0;
-	else
-		log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		logger -t $NAME "failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		return 1;
+	    # did we succeed?
+	    if [ $ERROR == 0 ]; then
+		    log_success_msg "$NAME: saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		    logger -t $NAME "saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		    return 0;
+	    else
+		    log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		    logger -t $NAME "failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		    return 1;
+	    fi
 	fi
 }
 
